### ISSUE TITLE
Create a multi sender of email since Notion API list

### ISSUE THREAD

**Issue by martin-lechene** [martin-lechene/martin-lechene#1]
# TODO

- [ ] Service for send email
- [ ] Connect to Notion API
- [ ] List history of email send
- [ ] CV Creator
